from prototype.tests.testmodels.DiagramEntityTest import *
from prototype.tests.testmodels.DiagramTest import *
from prototype.tests.testmodels.EntityTest import *
from prototype.tests.testmodels.ModelTest import *
from prototype.tests.testmodels.ProjectTest import *
from prototype.tests.testmodels.PropertyTest import *
from prototype.tests.testmodels.PropertyEquivalenceTest import *
from prototype.tests.testmodels.ProtoTableTest import *
from prototype.tests.testmodels.PrototypeTest import *
from prototype.tests.testmodels.RelationshipTest import *
