# -*- coding' : utf-8 -*-

__language ={
    'languaje' : 'en', 
             
    'Title_Main_Menu' : 'Main menu',
    'Text_Plugin_DD' : 'Drag to reorder',
    'Tooltip_New_Folder' : 'New folder',
    'Tooltip_New_Option' : 'New option',
    'Tooltip_Edit_Node' : 'Edit node',
    'Tooltip_Del_Node' : 'Delete node',
    'Tooltip_Save_Menu' : 'Save menu',
    'Tooltip_Reload_Menu' : 'Reload menu',
    'Tooltip_Reset_Menu' : 'Reset menu',
    'Msg_Window_New_Folder' : 'Please enter the folder name',
    'Title_Window_New_Folder' : 'Add menu',
    'Msg_Select_Folder' : 'Not selected folder',
    'Title_Window_Add_Option' : 'Add menu option',
    'MenuTree_Title_Fieldset' : 'Basic Information',
    'Title_Cancel_Button' : 'Cancel',
    'Title_Save_Button' : 'Save',
    'MenuTree_Text_Add_Event' : 'Add Event',
    'MenuTree_Text_Edit_Event' : 'Edit Event',
    'Msg_Saved' : 'Saving changes...',
    'Msg_Deleted_Event' : 'Deleting event...',
    'Toolbar_Text_Reset_Button' : 'Reset',
    'Msg_Invalid_Form' : 'OOPs!! Form is not valid',
    'Msg_Error_Save_Form' : 'Save form Failed',
    'Msg_Failed_Operation' : 'Operation failure',

    'Msg_View_In_New_Tab' : 'View in a new tab',
    'Label_Pagging_by_Page' : 'by page',
    'Label_Pagging_Result' : 'Results',
    'Label_Pagging_From' : 'from',
    'Label_Pagging_Page' : 'Page',
    'Label_Pagging_First_Page' : 'First page',
    'Label_Pagging_Next_Page' : 'Next page',
    'Label_Pagging_Previous_Page' : 'Previous page',
    'Label_Pagging_Last_Page' : 'Last page',
    'Text_Button_Upd_Grid' : 'Refresh',
    'Text_Toolbar_Remove_Filters' : 'Remove filters',
    'Text_UserInfo_Fullname' :'readOnly User',
    'Text_ComboFilterOp_Equal' : 'equal',
    'Text_ComboFilterOp_Containing' : 'containing',
    'Text_ComboFilterOp_Finishing' : 'ending with',
    'Text_ComboFilterOp_Starting' : 'starting with',
    'Text_ComboFilterOp_PlusThan' : 'larger than',
    'Text_ComboFilterOp_PlusEqualThan' : 'larger or equal than',
    'Text_ComboFilterOp_LessThan' : 'smaller than',
    'Text_ComboFilterOp_LessEqualThan' : 'smaller or equal than',
    'Text_ComboFilterOp_Null_Value' : 'Null value',
    'Text_Default_view' : 'Default',
  
    'List_Help_Meta_Config' : 'Meta Config',
    'List_Help_Form_Config' : 'Form Config',
    'List_Help_Add_Fields' : 'Add Fields',
    'List_Help_Add_Details' : 'Add Details',
    'List_Help_Reset_Meta' : 'Reset loaded meta',

    'Tooltip_Grid_Add_Form' : 'Add (form)',
    'Tooltip_Grid_Edit_Form' : 'Edit (form)',
    'Tooltip_Grid_Del_Record' : 'delete record',
    'Tooltip_Grid_Read_Only' : 'View ( read only )',
    'Tooltip_Grid_Add_Row' : 'Add row',
    'Tooltip_Grid_Copy_Row' : 'Copy row',
    'Msg_Select_Record' : 'No record selected',

    'Tooltip_Filter_Grid_Button' : 'Filter',
    'Text_Grid_Filter_By' :'filtered by',
    'Text_Toolbar_Advanced_Filter' :'Advanced filter QBE',
    'Text_Toolbar_Search_Field' : 'key word ..',
    'Text_Toolbar_Search_Combo' : 'select operator',
    'Text_Toolbar_In' : 'in ...',
    'Text_Plugin_DD_Grid' : 'Drag and drop to reorganize',
    'Text_Validate_Login_Button' : 'check',
    'Text_Forgotten_Password' : 'lost password',
    'Textfield_User_Login' : 'user',
    'Textfield_Password_Login' : 'password',
    'Title_Window_Email_Request' : 'your email',
    'Message_Enter_Email' : 'Enter your email',
    'Message_Success' : 'Success',
    'Message_Email_Forgotten_Password' : 'An email has been sent with the instructions',
    'Message_Error' : 'Error',
    'Message_Error_Login' : 'Impossible',

    'Text_Toolbar_Detail_Button' : 'Details',
    'Error_Loading_Detail_Button' : 'Error loading',
    'Text_Export_CSV' : 'Export CSV',
    'Tooltip_Export_CSV' : 'export in format csv',
    'Text_Plug' : 'Plug',
    'Text_Print' : 'Print',
    'Text_Grid' :'Grid',
    'Message_Succesful_Export_CSV' : 'export Csv  Ok',
    'Message_Failed_Export_CSV' : 'export Csv Failed',

    'Sorting_Text' : 'Sort by',
    'Toolbar_Text_Edit_Button' : 'Edit',
    'Tooltip_Switch_Edit_Mode' : 'Switch to edit mode',
    'Tooltip_Save_Exit_Edition_Button' : 'Save and exit edition mode',
    'Text_Continue_Button' : 'Continue',
    'Tooltip_Save_Continue_Edition_Button' : 'Save and continue',
    'Text_AutoSync' : 'AutoSync',
    'Text_Clasify_Button' : 'classify',
    'Tooltip_Clasify_Button' : 'Sorting options',
    'Tooltip_Printing_Options' : 'Printing Options',
    'Text_Actions_Button' : 'Actions',
    'Tooltip_Actions_Button' : 'The basic workflow',
    'Tooltip_Details_Button' : 'View details',
    'Text_Filters_Button' : 'Filters',
    'Tooltip_Filters_Button' : 'custom Filters',
    'Text_Close_Button' : 'Close',
    'Tooltip_Exit_Edit_Mode_Button' : 'Exit edit mode',

    'Text_Tabs_Button' : 'Tabs',
    'Tooltip_Tabs_Button' : 'Tabs',

    'Text_Sorters_Button' : 'Sorters',
    'Tooltip_Sorters_Button' : 'Sorters',

    'Tooltip_Open_HtmlEditor' : 'Open html editor',
    'Text_Return_Button' :'Return',
    'StatusBar_Message_Loading' : 'Loading...',
    'StatusBar_Message_Ready' : 'Ready',
    'StatusBar_Message_Sync' : 'Sync..',
    'StatusBar_Text_Clean_Button' : 'Clear',
    'StatusBar_Tooltip_Clean_Button' : 'clear status bar',
    'StatusBar_Text_Task_Button' : 'task',
    'StatusBar_Text_Close_Session' : 'Close session',
    'StatusBar_Error_When_Close_Session' : 'Action is not possible',
    'StatusBar_Text_Command_Button' : 'Command',

    'Text_Close_Tab' : 'Close Tab',
    'Text_Close_Other_Tabs' : 'Close Other Tabs',
    'Text_Close_All_Tabs' : 'Close All Tabs',

    'Text_Validation_Form' : 'The form has errors (click for details...)',
    'Text_Hide_Errors_Validation_Form' : 'Click again to hide the error list',
    'Text_Submit_Validation_Form' : 'Saving...',

    'Message_Error_SavePCI' : 'SavePCI Failed',
    'Message_Error_Reporting' : 'SheetReport Failed',


    'Title_Main_Panel' : 'RootPanel',
    'Title_Form_Panel' : 'Form',
    'Title_Panel_Tools' : 'Tools',

    'Tree_Concept_Details_Text' : 'text',
    'Tree_Concept_Details_Detail' : 'conceptDetail',
    'Tree_Details_Field' : 'detailField',

    'Protofield_Fields' : 'fields',
    'Protofield_Text' : 'text',
    'Protofield_Req' : 'requ',
    'Protofield_ROnly' : 'read only',
    'Protofield_Field_Type' : 'fieldtype',
    'Protofield_Zoom_Model' : 'zoomModel',
    'Protofield_fk_Field' : 'fkField',
    'Protofield_fk_Id' : 'fkId',
    'Protofield_Ix' : 'Ix',
    'Protofield_Header' : 'Header',
    'Protofield_Tooltip' : 'tooltip',
    'Protofield_Default_Value' : 'defaultValue',
    'Protofield_vType' : 'vType',
    'Protofield_choices' : 'choices',
    'ProtoPcl_Edition_Tool' : 'Meta edition tool',
    'ProtoPcl_Add_Instance' : 'Add instance of',
    'ProtoPcl_Del_Current' : 'Delete current',
    'ProtoToolbar_Save_Preview' : 'Save preview',
    'ProtoToolbar_Upd_Def' :'Update definition',
    'ProtoToolbar_Reload' :'Reload',
    'ProtoToolbar_Add_Node' :'Add node',
    'ProtoToolbar_Del_Current_Node' :'Delete current node',
    'ProtoToolbar_Show_Current_Meta' :'Show current Meta',
    'ProtoToolbar_Show_Help' : 'Show help',

    'Text_Enter_User_Login' : 'You must enter a user',
    'Text_Validating_Info_User' : 'Authenticating ...',
    'Text_No_Aplications' : 'No applications assigned',
    'Text_General_Information' :'Information',
    'Text_Error_In_Action' : 'The action was not possible',

    'Title_Aut_View' : 'Authorization',
    'Header_Column_Grid_App' : 'Application',
    'Header_Column_Grid_App_Id' : 'Id',
    'Header_Column_Grid_Env' : 'Environment',
    'Header_Column_Grid_Env_Id' : 'Id',

    'Title_Login_View' : 'Authentication',
    'Text_Combo_App' : 'Application',  
    'Text_Combo_Env' : 'Environment',
    'Text_Accept_Button' : 'Accept',
    'Text_Button_Load_App' :'Load application',
    'Text_Button_Close_Session' : 'Close session',

    'HelpQBE_Tooltip_PlusThan_Button' : 'larger than',
    'HelpQBE_Tooltip_LessThan_Button' : 'smaller than',
    'HelpQBE_Tooltip_PlusEqualThan_Button' : 'larger or equal than',
    'HelpQBE_Tooltip_LessEqualThan_Button' : 'smaller or equal than',
    'HelpQBE_Tooltip_Different_Button' : 'different',
    'HelpQBE_Tooltip_Between_Button' : 'between',
    'HelpQBE_Tooltip_Containing_Button' : 'containing',
    'HelpQBE_Label_Pagging_DisplayMsg' : 'records {0} - {1} of {2}',
    'HelpQBE_Label_Pagging_EmptyMsg' : 'no records',
    'HelpQBE_Window_Title' : 'Help QBE'

}
