# -*- coding' : utf-8 -*-

__language ={
    'languaje' : 'en', 
             
    'Title_Main_Menu' : 'Main menu',
    'MenuTree_DD_Text' : 'Drag to reorder',
    'Tooltip_New_Folder' : 'New folder',
    'Tooltip_New_Option' : 'New option',
    'Tooltip_Edit_Node' : 'Edit node',
    'Tooltip_Del_Node' : 'Delete node',
    'Tooltip_Save_Menu' : 'Save menu',
    'Tooltip_Reload_Menu' : 'Reload menu',
    'Tooltip_Reset_Menu' : 'Reset menu',
    'Msg_Window_New_Folder' : 'Please enter the folder name',
    'Title_Window_New_Folder' : 'Add menu',
    'Msg_Select_Folder' : 'Not selected folder',
    'Title_Window_Add_Option' : 'Add menu option',
    'MenuTree_Title_Fieldset' : 'Basic Information',
    
    'Text_Cancel_Button' : 'Cancel',
    'Text_Save_Button' : 'Save',
    'Text_New_Button' : 'New',
    'Text_Edit_Button' : 'Edit',
    'Text_SaveMs_Button' : 'SvMaster',
    'Text_SaveDt_Button' : 'SvDetails',
    
    'MenuTree_Text_Add_Event' : 'Add Event',
    'MenuTree_Text_Edit_Event' : 'Edit Event',
    'Msg_Saved' : 'Saving changes...',
    'Msg_Deleted_Event' : 'Deleting event...',

    'Msg_Invalid_Form' : 'OOPs!! Form is not valid',
    'Msg_Error_Save_Form' : 'Save form Failed',
    'Msg_Failed_Operation' : 'Operation failure',
    'Msg_Confirm_Delete_Operation' : 'Are you sure?',
    
    'Title_Msg_Confirm_Delete' : 'Confirm Delete',
    
    'GridNav_In_New_Tab' : 'View in a new tab',
    'GridNav_PageSize' : 'by page',
    'GridNav_Current' : 'Results',
    'GridNav_Total' : 'from',
    'GridNav_Page' : 'Page',
    'GridNav_First_Page' : 'First page',
    'GridNav_Next_Page' : 'Next page',
    'GridNav_Previous_Page' : 'Previous page',
    'GridNav_Last_Page' : 'Last page',
    'GridNav_Refresh' : 'Refresh',
    
    'Text_Toolbar_Remove_Filters' : 'Remove filters',
    'Text_UserInfo_Fullname' :'readOnly User',
    'Text_ComboFilterOp_Equal' : 'equal',
    'Text_ComboFilterOp_Containing' : 'containing',
    'Text_ComboFilterOp_Finishing' : 'ending with',
    'Text_ComboFilterOp_Starting' : 'starting with',
    'Text_ComboFilterOp_PlusThan' : 'larger than',
    'Text_ComboFilterOp_PlusEqualThan' : 'larger or equal than',
    'Text_ComboFilterOp_LessThan' : 'smaller than',
    'Text_ComboFilterOp_LessEqualThan' : 'smaller or equal than',
    'Text_ComboFilterOp_Null_Value' : 'Null value',
    'Text_Default_view' : 'Default',
  
    'MetaConfig_Meta_Config' : 'Meta',
    'MetaConfig_Form_Config' : 'Form',
    'MetaConfig_Custom_Config' : 'Custom',
    'MetaConfig_Base_Config' : 'Config',
    'MetaConfig_Add_Fields' : 'Fields',
    'MetaConfig_Add_Details' : 'Details',
    'MetaConfig_Reset_Meta' : 'Reset loaded meta',

    'GridBtn_Ttip_Add_Form' : 'Add (form)',
    'GridBtn_Ttip_Edit_Form' : 'Edit (form)',
    'GridBtn_Ttip_Del_Record' : 'Delete record',
    'GridBtn_Ttip_Read_Only' : 'View ( read only )',
    'GridBtn_Ttip_Add_Row' : 'Add row',
    'GridBtn_Ttip_Copy_Row' : 'Copy row',
    'GridBtn_Ttip_Edit_Diagram':'Edit diagram',
    'GridAction_NoRecord' : 'No record selected',

    'Tooltip_Filter_Grid_Button' : 'Filter',
    'Text_Grid_Filter_By' :'filtered by',
    'Text_Toolbar_Advanced_Filter' :'Advanced filter QBE',
    'Text_Toolbar_Search_Field' : 'key word ..',
    'Text_Toolbar_Search_Combo' : 'select operator',
    'Text_Toolbar_In' : 'in ...',
    'ProtoList_DD_Text' : 'Drag and drop to reorganize',
    
    'Text_Validate_Login_Button' : 'check',
    'Text_Forgotten_Password' : 'lost password',
    'Textfield_User_Login' : 'user',
    'Textfield_Password_Login' : 'password',
    'Title_Window_Email_Request' : 'your email',
    'Message_Enter_Email' : 'Enter your email',
    'Message_Success' : 'Success',
    'Message_Email_Forgotten_Password' : 'An email has been sent with the instructions',
    'Message_Error' : 'Error',
    'Message_Error_Login' : 'Impossible',

    'Grid_Detail_Title' : 'Details',
    'Grid_Detail_Error' : 'Error loading',
    'Grid_ExportCSV' : 'Export CSV',
    'Grid_ExportCSV_Ttip' : 'export in format csv',
    'Grid_ExportCSV_Ok' : 'export Csv  Ok',
    'Grid_ExportCSV_Err' : 'export Csv Failed',
    
    'Text_Plug' : 'Plug',
    'Text_Print' : 'Print',
    'Text_Config' : 'Config',
    'Text_Grid' :'Grid',

    'Grid_Sort_Title' : 'Sort by',
    'Grid_Edit_Title' : 'Edit',
    'Grid_Edit_Ttip' : 'Switch to edit mode',
    'Grid_EditSave_Title' : 'Save and exit edition mode',
    'Grid_EditSaveCont_Title' : 'Continue',
    'Grid_EditSaveCont_Ttip' : 'Save and continue',
    'Grid_EditAutoSync_Title' : 'AutoSync',
    
    'Text_Clasify_Button' : 'classify',
    'Tooltip_Clasify_Button' : 'Sorting options',
    'Tooltip_Printing_Options' : 'Printing Options',
    'Tooltip_Config_Button' : 'Config Options',
    'Text_Actions_Button' : 'Actions',
    'Tooltip_Actions_Button' : 'The actions',
    'Tooltip_Details_Button' : 'View details',
    'Text_Filters_Button' : 'Filters',
    'Tooltip_Filters_Button' : 'custom Filters',
    'Text_Close_Button' : 'Close',
    
    'Text_Exit_Edit_Mode_Button' : 'Edit Off',
    'Tooltip_Exit_Edit_Mode_Button' : 'Exit edit mode',

    'Text_Tabs_Button' : 'Tabs',
    'Tooltip_Tabs_Button' : 'Tabs',

    'Text_Sorters_Button' : 'Sorters',
    'Tooltip_Sorters_Button' : 'Sorters',

    'Tooltip_Open_HtmlEditor' : 'Open html editor',
    'Text_Return_Button' :'Return',
    'StatusBar_Message_Loading' : 'Loading...',
    'StatusBar_Message_Ready' : 'Ready',
    'StatusBar_Message_Sync' : 'Sync..',
    'StatusBar_Text_Clean_Button' : 'Clear',
    'StatusBar_Tooltip_Clean_Button' : 'clear status bar',
    'StatusBar_Text_Task_Button' : 'task',
    'StatusBar_Text_Close_Session' : 'Close session',
    'StatusBar_Error_When_Close_Session' : 'Action is not possible',
    'StatusBar_Text_Command_Button' : 'Command',

    'Text_Close_Tab' : 'Close Tab',
    'Text_Close_Other_Tabs' : 'Close Other Tabs',
    'Text_Close_All_Tabs' : 'Close All Tabs',

    'Text_Validation_Form' : 'The form has errors (click for details...)',
    'Text_Hide_Errors_Validation_Form' : 'Click again to hide the error list',
    'Text_Submit_Validation_Form' : 'Saving...',

    'Message_Error_SaveProtoObj' : 'SaveProtoObj Failed',
    'Message_Error_Reporting' : 'SheetReport Failed',

    'Title_Main_Panel' : 'RootPanel',
    'Title_Form_Panel' : 'Form',
    'Title_Panel_Tools' : 'Tools',

    'Tree_Concept_Details_Text' : 'text',
    'Tree_Concept_Details_Detail' : 'conceptDetail',
    'Tree_Details_Field' : 'detailField',

    'Protofield_Fields' : 'fields',
    'Protofield_Text' : 'text',
    'Protofield_Req' : 'requ',
    'Protofield_ROnly' : 'read only',
    'Protofield_Field_Type' : 'fieldtype',
    'Protofield_Zoom_Model' : 'zoomModel',
    'Protofield_fk_Field' : 'fkField',
    'Protofield_fk_Id' : 'fkId',
    'Protofield_Ix' : 'Ix',
    'Protofield_Header' : 'Header',
    'Protofield_Tooltip' : 'tooltip',
    'Protofield_Default_Value' : 'prpDefault',
    'Protofield_vType' : 'vType',
    'Protofield_choices' : 'choices',
    'ProtoPcl_Edition_Tool' : 'Meta edition tool',
    'ProtoPcl_Add_Instance' : 'Add instance of',
    'ProtoPcl_Del_Current' : 'Delete current',
    'ProtoToolbar_Save_As' : 'Save as',
    'ProtoToolbar_Upd_Def' :'Update definition',
    'ProtoToolbar_Reload' :'Reload',
    'ProtoToolbar_Add_Node' :'Add node',
    'ProtoToolbar_Del_Current_Node' :'Delete current node',
    'ProtoToolbar_Show_Current_Meta' :'Show current Meta',
    'ProtoToolbar_Show_Help' : 'Show help',

    'Text_Enter_User_Login' : 'You must enter a user',
    'Text_Validating_Info_User' : 'Authenticating ...',
    'Text_No_Aplications' : 'No applications assigned',
    'Text_General_Information' :'Information',
    'Text_Error_In_Action' : 'The action was not possible',

    'Title_Aut_View' : 'Authorization',
    'Header_Column_Grid_App' : 'Application',
    'Header_Column_Grid_App_Id' : 'Id',
    'Header_Column_Grid_Env' : 'Environment',
    'Header_Column_Grid_Env_Id' : 'Id',

    'Title_Login_View' : 'Authentication',
    'Text_Combo_App' : 'Application',  
    'Text_Combo_Env' : 'Environment',
    'Text_Accept_Button' : 'Accept',
    'Text_Button_Load_App' :'Load application',
    'Text_Button_Close_Session' : 'Close session',

    'HelpQBE_Tooltip_PlusThan_Button' : 'larger than',
    'HelpQBE_Tooltip_LessThan_Button' : 'smaller than',
    'HelpQBE_Tooltip_PlusEqualThan_Button' : 'larger or equal than',
    'HelpQBE_Tooltip_LessEqualThan_Button' : 'smaller or equal than',
    'HelpQBE_Tooltip_Different_Button' : 'different',
    'HelpQBE_Tooltip_Between_Button' : 'between',
    'HelpQBE_Tooltip_Containing_Button' : 'containing',
    'HelpQBE_GridNav_DisplayMsg' : 'records {0} - {1} of {2}',
    'HelpQBE_GridNav_EmptyMsg' : 'no records',
    'HelpQBE_Window_Title' : 'Help QBE',
    
    
    'Menu_Update_Diagram' : 'Update diagram',
    'Menu_Search_Table' : 'Add table from DB',
    'Menu_Manage_Diagrams' : 'Manage diagrams',
    'Menu_Database_Title' : 'Database',
    'Menu_Add_Recursive_Association' : 'Add recursive association',
    'Menu_Add_Input_Port' : 'Add input port',
    'Menu_Add_Output_Port' : 'Add output port',
    'Menu_Remove_Unused_Ports' : 'Remove unused ports',
    
    'Text_Undo_Button' : 'Undo',
    'Text_Redo_Button' : 'Redo',
    'Text_Delete_Button' : 'Delete',
    'Text_ZoomIn_Button' : 'Zoom in',
    'Text_ZoomOut_Button' : 'Zoom out',
    'Text_Save_Diagram_Button' : 'Save diagram',
    'Text_Commit_Changes_Button' : 'Commit changes to DB',
    'Text_Add_Button' : 'Add',
    'Text_UpdateDiagram_Button' : 'Update diagram',
    'Text_OpenDiagram_Button' : 'Open diagram',
    'Text_Export_Image': 'Print diagram',
    
    'GridColumn_Name' : 'Name',
    'GridColumn_Datatype' : 'Datatype',
    'GridColumn_Required' : 'Required',
    
    'Title_Attributes' : 'Attributes',
    'Title_Work_Diagram' : 'Work diagram: ',
    'Title_Diagrams' : 'Diagrams',
    
    'Label_Dependency':'Dependency',
    'Label_Table_Name':'Table name',
    'Label_Connector_Name':'Connector name',
    
    'Message_Saving_Data' : 'Saving your data, please wait...',
    'Message_Creating_Objects' : 'Creating objects in Database, please wait...',
    'Message_Diagram_Synchronized' : 'The diagram has been synchronized!',
    'Message_Error_Diagram_Synchronized' : 'The system was unable to synchronize the diagram, please try again later!',
    'Message_Add_Table_Canvas' : 'Adding tables to canvas, please wait...',
    
    'Warning_Delete_Active_Diagram' : 'You cannot delete the active diagram!',
    'Warning_Diagram_Already_Open' : 'The selected diagram is already opened!',
    
    'Label_Left': 'Left',
    'Label_Right': 'Right',
    'Label_Top': 'Top',
    'Label_Bottom': 'Bottom'
}
