# -*- coding' : utf-8 -*-

__language ={
    'languaje' : 'es', 
             
    'Title_Main_Menu' : 'Composants du Dictionnaire',
    'Text_Plugin_DD' : 'Faites glisser pour réorganiser',
    'Tooltip_New_Folder' : 'nouveau dossier',
    'Tooltip_New_Option' : 'nouvelle option',
    'Tooltip_Edit_Node' : 'modifier noeud',
    'Tooltip_Del_Node' : 'supprimer noeud',
    'Tooltip_Save_Menu' : 'menu de sauvegarde',
    'Tooltip_Reload_Menu' : 'recharger le menu',
    'Tooltip_Reset_Menu' : 'réinitialiser le menu',
    'Msg_Window_New_Folder' : "S'il vous plaît entrez le nom du dossier",
    'Title_Window_New_Folder' : "Ajout d'un menu",
    'Msg_Select_Folder' : 'Non sélectionné le dossier',
    'Title_Window_Add_Option' : "Ajout d'une option de menu",
    'MenuTree_Title_Fieldset' : 'Information de base',
    'Title_Cancel_Button' : 'annuler',
    'Title_Save_Button' : 'Sauver',
    'MenuTree_Text_Add_Event' : "Ajouter l'événement",
    'MenuTree_Text_Edit_Event' : "Modifier l'événement",
    'Msg_Saved' : 'Enregistrement des modifications ...',
    'Msg_Deleted_Event' : "Suppression d'événement ...",
    'Toolbar_Text_Reset_Button' : 'Réinitialiser',
    'Msg_Invalid_Form' : "OOPS! La forme n'est pas valide",
    'Msg_Error_Save_Form' : 'Enregistrer sous forme Échec',
    'Msg_Failed_Operation' : "échec de l'opération",

    'Msg_View_In_New_Tab' : 'Voir dans un nouvel onglet',
    'Label_Pagging_by_Page' : 'par page',
    'Label_Pagging_Result' : 'Résultats',
    'Label_Pagging_From' : 'de',
    'Label_Pagging_Page' : 'Page',
    'Label_Pagging_First_Page' : 'Première page',
    'Label_Pagging_Next_Page' : 'Page suivante',
    'Label_Pagging_Previous_Page' : 'Page précédente',
    'Label_Pagging_Last_Page' : 'Dernière page',
    'Text_Button_Upd_Grid' : 'Actualiser',
    'Text_Toolbar_Remove_Filters' : 'Supprimer les filtres',
    'Text_UserInfo_Fullname' :'utilisateur en lecture seule',
    'Text_ComboFilterOp_Equal' : 'égal',
    'Text_ComboFilterOp_Containing' : 'qui contient',
    'Text_ComboFilterOp_Finishing' : 'qui finisse par',
    'Text_ComboFilterOp_Starting' : 'qui commence par',
    'Text_ComboFilterOp_PlusThan' : 'plus grand que',
    'Text_ComboFilterOp_PlusEqualThan' : 'plus grand ou égal que',
    'Text_ComboFilterOp_LessThan' : 'plus petit que',
    'Text_ComboFilterOp_LessEqualThan' : 'plus petit ou égal que',
    'Text_ComboFilterOp_Null_Value' : 'valeur nulle',
    'Text_Default_view' : 'Par défaut',
  
    'List_Help_Meta_Config' : 'Méta config',
    'List_Help_Form_Config' : 'Former config',
    'List_Help_Add_Fields' : 'ajouter des champs',
    'List_Help_Add_Details' : 'ajouter des détails',
    'List_Help_Reset_Meta' : 'Réinitialiser méta chargé',

    'Tooltip_Grid_Add_Form' : 'Ajouter (formulaire)',
    'Tooltip_Grid_Edit_Form' : 'Editer (formulaire)',
    'Tooltip_Grid_Del_Record' : 'Effacer ligne',
    'Tooltip_Grid_Read_Only' : 'Voir ( lecture seulement )',
    'Tooltip_Grid_Add_Row' : 'Ajouter ligne',
    'Tooltip_Grid_Copy_Row' : 'Copier ligne',
    'Msg_Select_Record' : 'aucun enregistrement sélectionné',

    'Tooltip_Filter_Grid_Button' : 'Filtrer',
    'Text_Grid_Filter_By' : 'filtrés par',
    'Text_Toolbar_Advanced_Filter' :'Filtre avancé QBE',
    'Text_Toolbar_Search_Field' : 'mots-clés recherchés ..',
    'Text_Toolbar_Search_Combo' : 'sélectionner opérator',
    'Text_Toolbar_In' : 'dans ...',
    'Text_Plugin_DD_Grid' : 'Glisser-déposer pour réorganiser',
    'Text_Validate_Login_Button' : 'vérifier',
    'Text_Forgotten_Password' : 'mot de passe perdu',
    'Textfield_User_Login' : 'utilisateur',
    'Textfield_Password_Login' : 'mot de passe',
    'Title_Window_Email_Request' : 'votre email',
    'Message_Enter_Email' : 'Saisissez votre email',
    'Message_Success' : 'Succès',
    'Message_Email_Forgotten_Password' : 'Un email a été envoyée avec les instructions',
    'Message_Error' : 'Erreur',
    'Message_Error_Login' : 'Impossible',

    'Text_Toolbar_Detail_Button' : 'détails',
    'Error_Loading_Detail_Button' : 'erreur lors du chargement',
    'Text_Export_CSV' : 'Export CSV',
    'Tooltip_Export_CSV' : 'exportation en format CSV',
    'Text_Plug' : 'Plug',
    'Text_Print' : 'Imprimer',
    'Text_Grid' :'Grille',
    'Message_Succesful_Export_CSV' : 'Export CSV Ok',
    'Message_Failed_Export_CSV' : "Échec de l'exportation CSV",

    'Sorting_Text' : 'Classer par',
    'Toolbar_Text_Edit_Button' : 'Editer',
    'Tooltip_Switch_Edit_Mode' : 'Changer à mode edition',
    'Tooltip_Save_Exit_Edition_Button' : "Sauvegardez et quittez le mode d'édition",
    'Text_Continue_Button' : 'continuer',
    'Tooltip_Save_Continue_Edition_Button' : 'Enregistrer et continuer',
    'Text_AutoSync' : 'AutoSync',
    'Text_Clasify_Button' : 'Classer',
    'Tooltip_Clasify_Button' : 'Options de classement',
    'Tooltip_Printing_Options' : "Options d'impression",
    'Text_Actions_Button' : 'Actes',
    'Tooltip_Actions_Button' : 'Le flux de production de base',
    'Tooltip_Details_Button' : 'Voir détails',
    'Text_Filters_Button' : 'Filtres',
    'Tooltip_Filters_Button' : 'Filtres personnalisés',
    'Text_Close_Button' : 'Fermer',
    'Tooltip_Exit_Edit_Mode_Button' : 'Fermer mode édition',

    'Text_Tabs_Button' : 'Tabs',
    'Tooltip_Tabs_Button' : 'Tabs',

    'Text_Sorters_Button' : 'Sorters',
    'Tooltip_Sorters_Button' : 'Sorters',

    'Tooltip_Open_HtmlEditor' : 'Ouvrir éditeur html',
    'Text_Return_Button' :'Rentrer',
    'StatusBar_Message_Loading' : 'Chargement ...',
    'StatusBar_Message_Ready' : 'Prête',
    'StatusBar_Message_Sync' : 'Sync..',
    'StatusBar_Text_Clean_Button' : 'Décochez',
    'StatusBar_Tooltip_Clean_Button' : "barre d'état clair",
    'StatusBar_Text_Task_Button' : 'tâche',
    'StatusBar_Text_Close_Session' : 'Fermer la session',
    'StatusBar_Error_When_Close_Session' : "Action n'est pas possible",
    'StatusBar_Text_Command_Button' : 'commandement',

    'Text_Close_Tab' : "Fermer l'onglet",
    'Text_Close_Other_Tabs' : 'Fermer les autres onglets',
    'Text_Close_All_Tabs' : 'Fermer tous les onglets',

    'Text_Validation_Form' : 'Le formulaire contient des erreurs (cliquez pour les détails ...)',
    'Text_Hide_Errors_Validation_Form' : 'Cliquez à nouveau pour masquer la liste des erreurs',
    'Text_Submit_Validation_Form' : 'Sauvegarde en cours ...',

    'Message_Error_SavePCI' : 'Échec SavePCI',
    'Message_Error_Reporting' : 'Échec SheetReport',


    'Title_Main_Panel' : 'RootPanel',
    'Title_Form_Panel' : 'Formulaire',
    'Title_Panel_Tools' : 'Outils',

    'Tree_Concept_Details_Text' : 'texte',
    'Tree_Concept_Details_Detail' : 'détail de l concept',
    'Tree_Details_Field' : 'détail de l champ ',

    'Protofield_Fields' : 'champs',
    'Protofield_Text' : 'texte',
    'Protofield_Req' : 'req',
    'Protofield_ROnly' : 'lecture seulement',
    'Protofield_Field_Type' : 'fieldtype',
    'Protofield_Zoom_Model' : 'zoomModel',
    'Protofield_fk_Field' : 'fkField',
    'Protofield_fk_Id' : 'fkId',
    'Protofield_Ix' : 'Ix',
    'Protofield_Header' : 'Header',
    'Protofield_Tooltip' : 'tooltip',
    'Protofield_Default_Value' : 'valeur par défaut',
    'Protofield_vType' : 'vType',
    'Protofield_choices' : 'les choix',
    'ProtoPcl_Edition_Tool' : 'Meta édition outil',
    'ProtoPcl_Add_Instance' : 'Ajouter instance de',
    'ProtoPcl_Del_Current' : 'Supprimer actuelle',
    'ProtoToolbar_Save_Preview' : 'Enregistrer la prévisualisation',
    'ProtoToolbar_Upd_Def' :"mise à jour de définition",
    'ProtoToolbar_Reload' :'rechargement',
    'ProtoToolbar_Add_Node' :'Ajouter un noeud',
    'ProtoToolbar_Del_Current_Node' :'Delet noeud actuel',
    'ProtoToolbar_Show_Current_Meta' :'Voir Meta actuelle',
    'ProtoToolbar_Show_Help' : "Afficher l'aide",

    'Text_Enter_User_Login' : 'Vous devez entrer un nom',
    'Text_Validating_Info_User' : 'Authentifiant ...',
    'Text_No_Aplications' : 'Pas applications assignées',
    'Text_General_Information' :"d'informations",
    'Text_Error_In_Action' : "L'action n'était pas possible",

    'Title_Aut_View' : 'Autorisation',
    'Header_Column_Grid_App' : 'Application',
    'Header_Column_Grid_App_Id' : 'Id',
    'Header_Column_Grid_Env' : 'Environment',
    'Header_Column_Grid_Env_Id' : 'Id',

    'Title_Login_View' : 'Authentification',
    'Text_Combo_App' : 'Application',  
    'Text_Combo_Env' : 'Environment',
    'Text_Accept_Button' : 'Accepter',
    'Text_Button_Load_App' :'Application de la charge',
    'Text_Button_Close_Session' : 'Fermer la session',

    'HelpQBE_Tooltip_PlusThan_Button' : 'plus grand que',
    'HelpQBE_Tooltip_LessThan_Button' : 'plus petit que',
    'HelpQBE_Tooltip_PlusEqualThan_Button' : 'plus grand ou égal que',
    'HelpQBE_Tooltip_LessEqualThan_Button' : 'plus petit ou égal que',
    'HelpQBE_Tooltip_Different_Button' : 'différent',
    'HelpQBE_Tooltip_Between_Button' : 'entre',
    'HelpQBE_Tooltip_Containing_Button' : 'qui contient',
    'HelpQBE_Label_Pagging_DisplayMsg' : 'registres {0} - {1} de {2}',
    'HelpQBE_Label_Pagging_EmptyMsg' : 'no registres',
    'HelpQBE_Window_Title' : 'Aider QBE'

}