# -*- coding' : utf-8 -*-

__language ={
    'languaje' : 'es', 
    
    'Title_Main_Menu' : 'Menu Principal',
    'MenuTree_DD_Text' : 'Arrastre para reordenar',
    'Tooltip_New_Folder' : 'Nueva carpeta',
    'Tooltip_New_Option' : 'Nueva opción',
    'Tooltip_Edit_Node' : 'Modificar nodo',
    'Tooltip_Del_Node' : 'Eliminar nodo',
    'Tooltip_Save_Menu' : 'Guardar menu',
    'Tooltip_Reload_Menu' : 'Recargar menu',
    'Tooltip_Reset_Menu' : 'Reiniciar menu',
    'Msg_Window_New_Folder' : 'Por favor, ingrese un nombre de carpeta',
    'Title_Window_New_Folder' : 'Agregar opción a menu',
    'Msg_Select_Folder' : 'Ninguna carpeta seleccionada',
    'Title_Window_Add_Option' : 'Agregar opción al menu',
    'MenuTree_Title_Fieldset' :'Información básica',
    
    'Text_Cancel_Button' : 'Cancelar',
    'Text_Save_Button' : 'Guardar',
    'Text_New_Button' : 'Nuevo',
    'Text_Edit_Button' : 'Editar',
    'Text_SaveMs_Button' : 'Guardar',
    'Text_SaveDt_Button' : 'Guardar Det',
    
    'MenuTree_Text_Add_Event' : 'Agregar Evento',
    'MenuTree_Text_Edit_Event' : 'Modificar Evento',
    'Msg_Saved' : 'Guardando cambios...',
    'Msg_Deleted_Event' : 'Eliminando evento...',

    'Msg_Invalid_Form' : 'OOPs!! Formulario no es válido',
    'Msg_Error_Save_Form' : 'Error al guardar formulario',
    'Msg_Failed_Operation' : 'Operación fallida',
    'Msg_Confirm_Delete_Operation' : 'Está seguro?',

    'Title_Msg_Confirm_Delete' : 'Confirmar eliminación',
    
    'GridNav_In_New_Tab' : 'Ver en una nueva pestaña',
    'GridNav_PageSize' : 'por página',
    'GridNav_Current' : 'Resultados',
    'GridNav_Total' : 'de',
    'GridNav_Page' : 'Página',
    'GridNav_First_Page' : 'Primera página',
    'GridNav_Next_Page' : 'Página siguiente',
    'GridNav_Previous_Page' : 'Página anterior',
    'GridNav_Last_Page' : 'Ultima página',
    'GridNav_Refresh' : 'Actualizar',
    
    'Text_Toolbar_Remove_Filters' : 'Quitar filtros',
    'Text_UserInfo_Fullname' : 'usuario solo lectura',
    'Text_ComboFilterOp_Equal' : 'igual',
    'Text_ComboFilterOp_Containing' : 'contiene',
    'Text_ComboFilterOp_Finishing' : 'finaliza con',
    'Text_ComboFilterOp_Starting' : 'inicia con',
    'Text_ComboFilterOp_PlusThan' : 'mayor que',
    'Text_ComboFilterOp_PlusEqualThan' : 'mayor o igual que',
    'Text_ComboFilterOp_LessThan' : 'menor que',
    'Text_ComboFilterOp_LessEqualThan' : 'menor o igual que',
    'Text_ComboFilterOp_Null_Value' : 'Valor nulo',
    'Text_Default_view' : 'Por defecto',

    'MetaConfig_Meta_Config' : 'Metadata',
    'MetaConfig_Form_Config' : 'Formulario',
    'MetaConfig_Custom_Config' : 'Personalizar',
    'MetaConfig_Base_Config' : 'Configuración',
    'MetaConfig_Add_Fields' : 'Campos',
    'MetaConfig_Add_Details' : 'Detalles',
    'MetaConfig_Reset_Meta' : 'Restablecer metadata cargada',

    'GridBtn_Ttip_Add_Form' : 'Agregar (formulario)',
    'GridBtn_Ttip_Edit_Form' : 'Editar (formulario)',
    'GridBtn_Ttip_Del_Record' : 'Borrar registro',
    'GridBtn_Ttip_Read_Only' : 'Ver ( sólo lectura )',
    'GridBtn_Ttip_Add_Row' : 'Agregar fila',
    'GridBtn_Ttip_Copy_Row' : 'Copiar fila',
    'GridBtn_Ttip_Edit_Diagram':'Éditer diagramme',
    'GridAction_NoRecord' : 'Ningún registro seleccionado',

    'Tooltip_Filter_Grid_Button' : 'Filtrar',
    'Text_Grid_Filter_By' : 'filtrado por',
    'Text_Toolbar_Advanced_Filter' : 'Filtro QBE avanzado',
    'Text_Toolbar_Search_Field' : 'palabra clave ..',
    'Text_Toolbar_Search_Combo' : 'seleccione el operador',
    'Text_Toolbar_In' :'en ...',
    'ProtoList_DD_Text' : 'Arrastre y suelte para organizar',
    
    'Text_Validate_Login_Button' : 'validar',
    'Text_Forgotten_Password' : 'contraseña olvidada',
    'Textfield_User_Login' : 'Usuario',
    'Textfield_Password_Login' : 'Contraseña',
    'Title_Window_Email_Request' : 'su email',
    'Message_Enter_Email' : 'Ingrese su email',
    'Message_Success' : 'Todo bien',
    'Message_Email_Forgotten_Password' : 'Un email se ha enviado con las instrucciones',
    'Message_Error' : 'Error',
    'Message_Error_Login' : 'Imposible',

    'Grid_Detail_Title' : 'Detalles',
    'Grid_Detail_Error' : 'Error cargando',
    'Grid_ExportCSV' : 'Exportar CSV',
    'Grid_ExportCSV_Ttip' : 'Exportar en formato csv',
    'Grid_ExportCSV_Ok' : 'Exportado a CSV correctamente',
    'Grid_ExportCSV_Err' : 'Error al exportar a CSV',
    
    'Text_Plug' : 'Conexión',
    'Text_Grid' : 'Grilla',
    'Text_Print' : 'Imprimir',
    'Text_Config' : 'Configurar',

    'Grid_Sort_Title' : 'Ordenar por',
    'Grid_Edit_Title' : 'Editar',
    'Grid_Edit_Ttip' : 'Cambiar a modo edición',
    'Grid_EditSave_Title' : 'Guardar y salir de modo edición',
    'Grid_EditSaveCont_Title' :'Continuar',
    'Grid_EditSaveCont_Ttip' : 'Guardar y continuar',
    'Grid_EditAutoSync_Title' : 'Sincronización automática',
    
    'Text_Clasify_Button' : 'Clasificar',
    'Tooltip_Clasify_Button' : 'Opciones de ordenamiento',
    'Tooltip_Printing_Options' : 'Opciones de impresión',
    'Tooltip_Config_Button' : 'Config Options',
    'Text_Actions_Button' : 'Acciones',
    'Tooltip_Actions_Button' : 'Acciones de la entidad',
    'Tooltip_Details_Button' : 'Ver detalles',
    'Text_Filters_Button' : 'Filtros',
    'Tooltip_Filters_Button' : 'Filtros personalizados',
    'Text_Close_Button' : 'Cerrar',
    
    'Text_Exit_Edit_Mode_Button' : 'Salir modo édición',
    'Tooltip_Exit_Edit_Mode_Button' : 'Salir de modo de edición',

    'Text_Tabs_Button' : 'Pestañas',
    'Tooltip_Tabs_Button' : 'Pestañas',

    'Text_Sorters_Button' : 'Clasificadores',
    'Tooltip_Sorters_Button' : 'Clasificadores',

    'Tooltip_Open_HtmlEditor' : 'Abrir editor HTML',
    'Text_Return_Button' : 'Volver',
    'StatusBar_Message_Loading' : 'Cargando...',
    'StatusBar_Message_Ready' :'Listo',
    'StatusBar_Message_Sync' : 'Sincronizar..',
    'StatusBar_Text_Clean_Button' : 'Limpiar',
    'StatusBar_Tooltip_Clean_Button' : 'limpiar barra de estado',
    'StatusBar_Text_Task_Button' : 'tarea',
    'StatusBar_Text_Close_Session' : 'Cerrar Sesión',
    'StatusBar_Error_When_Close_Session' : 'La accion no es posible',
    'StatusBar_Text_Command_Button' : 'Comando',

    'Text_Close_Tab' : 'Cerrar pestaña',
    'Text_Close_Other_Tabs' : 'Cerrar demás pestañas',
    'Text_Close_All_Tabs' : 'Cerrar todas las pestañas',

    'Text_Validation_Form' : 'El formulario tiene errores (Haga clic para mas detalles...)',
    'Text_Hide_Errors_Validation_Form' : 'Haga clic de nuevo para ocultar la lista de errores',
    'Text_Submit_Validation_Form' : 'Guardando...',

    'Message_Error_SaveProtoObj' : 'Error al guardar PCI',
    'Message_Error_Reporting' : 'Error en lanzar informe',

    'Title_Main_Panel' : 'Panel principal',
    'Title_Form_Panel' : 'Elementos del formulario',
    'Title_Panel_Tools' : 'Herramientas del formulario',

    'Tree_Concept_Details_Text' : 'texto',
    'Tree_Concept_Details_Detail' : 'detalle del concepto',
    'Tree_Details_Field' : 'detalle del campo',


    'Protofield_Fields' : 'campos',
    'Protofield_Text' : 'texto',
    'Protofield_Req' : 'requerido',
    'Protofield_ROnly' : 'solo lectura',
    'Protofield_Field_Type' : 'tipo de campo',
    'Protofield_Zoom_Model' : 'Modelo de zoom',
    'Protofield_fk_Field' :'Llave extrangera',
    'Protofield_fk_Id' : 'ID llave extrangera',
    'Protofield_Ix' : 'Ix',
    'Protofield_Header' : 'Encabezado',
    'Protofield_Tooltip' : 'tooltip',
    'Protofield_Default_Value' : 'valor por defecto',
    'Protofield_vType' : 'Tipo de validación',
    'Protofield_choices' : 'Opciones',
    'ProtoPcl_Edition_Tool' : 'Herramienta edición Metadata',
    'ProtoPcl_Add_Instance' : 'Agregar instancia de',
    'ProtoPcl_Del_Current' : 'Borrar actual',
    'ProtoToolbar_Save_As' : 'Guardar como',
    'ProtoToolbar_Upd_Def' :'Actualizar definición',
    'ProtoToolbar_Reload' :'Recargar',
    'ProtoToolbar_Add_Node' :'Agregar nodo',
    'ProtoToolbar_Del_Current_Node' :'Borrar el nodo actual',
    'ProtoToolbar_Show_Current_Meta' :'Mostrar Metadata actual',
    'ProtoToolbar_Show_Help' : 'Mostrar ayuda',

    'Text_Enter_User_Login' : 'Debe ingresar un usuario',
    'Text_Validating_Info_User' : 'Autenticación ...',
    'Text_No_Aplications' : 'No hay aplicaciones asignadas',
    'Text_General_Information' : 'Información',
    'Text_Error_In_Action' : 'La acción no fue posible',

    'Title_Aut_View' : 'Autorización',
    'Header_Column_Grid_App' : 'Aplicación',
    'Header_Column_Grid_App_Id' : 'Id',
    'Header_Column_Grid_Env' : 'Entorno',
    'Header_Column_Grid_Env_Id' : 'Id',

    'Title_Login_View' : 'Autenticación',
    'Text_Combo_App' : 'Aplicación',
    'Text_Combo_Env' : 'Entorno',
    'Text_Accept_Button' : 'Aceptar',
    'Text_Button_Load_App' : 'Cargar aplicación ',
    'Text_Button_Close_Session' : 'Cerrar sesión',

    'HelpQBE_Tooltip_PlusThan_Button' : 'mayor que',
    'HelpQBE_Tooltip_LessThan_Button' : 'menor que',
    'HelpQBE_Tooltip_PlusEqualThan_Button' : 'mayor o igual que',
    'HelpQBE_Tooltip_LessEqualThan_Button' : 'menor o igual que',
    'HelpQBE_Tooltip_Different_Button' : 'diferente',
    'HelpQBE_Tooltip_Between_Button' : 'entre',
    'HelpQBE_Tooltip_Containing_Button' : 'contiene',
    'HelpQBE_GridNav_DisplayMsg' : 'registros {0} - {1} de {2}',
    'HelpQBE_GridNav_EmptyMsg' : 'no hay registros', 
    'HelpQBE_Window_Title' : 'Asistente QBE',
    
    
    'Menu_Update_Diagram' : 'Update diagram',
    'Menu_Search_Table' : 'Add table from DB',
    'Menu_Manage_Diagrams' : 'Manage diagrams',
    'Menu_Database_Title' : 'Database',
    'Menu_Add_Recursive_Association' : 'Add recursive association',
    'Menu_Add_Input_Port' : 'Add input port',
    'Menu_Add_Output_Port' : 'Add output port',
    'Menu_Remove_Unused_Ports' : 'Remove unused ports',
    
    'Text_Undo_Button' : 'Undo',
    'Text_Redo_Button' : 'Redo',
    'Text_Delete_Button' : 'Delete',
    'Text_ZoomIn_Button' : 'Zoom in',
    'Text_ZoomOut_Button' : 'Zoom out',
    'Text_Save_Diagram_Button' : 'Save diagram',
    'Text_Commit_Changes_Button' : 'Commit changes to DB',
    'Text_Add_Button' : 'Add',
    'Text_UpdateDiagram_Button' : 'Update diagram',
    'Text_OpenDiagram_Button' : 'Open diagram',
    'Text_Export_Image': 'Print diagram',
    
    'GridColumn_Name' : 'Name',
    'GridColumn_Datatype' : 'Datatype',
    'GridColumn_Required' : 'Required',
    
    'Title_Attributes' : 'Attributes',
    'Title_Work_Diagram' : 'Work diagram: ',
    'Title_Diagrams' : 'Diagrams',
    
    'Label_Dependency':'Dependency',
    'Label_Table_Name':'Table name',
    'Label_Connector_Name':'Connector name',
    
    'Message_Saving_Data' : 'Saving your data, please wait...',
    'Message_Creating_Objects' : 'Creating objects in Database, please wait...',
    'Message_Diagram_Synchronized' : 'The diagram has been synchronized!',
    'Message_Error_Diagram_Synchronized' : 'The system was unable to synchronize the diagram, please try again later!',
    'Message_Add_Table_Canvas' : 'Adding tables to canvas, please wait...',
    
    'Warning_Delete_Active_Diagram' : 'You cannot delete the active diagram!',
    'Warning_Diagram_Already_Open' : 'The selected diagram is already opened!',
    
    'Label_Left': 'Left',
    'Label_Right': 'Right',
    'Label_Top': 'Top',
    'Label_Bottom': 'Bottom'
}