# -*- coding' : utf-8 -*-

__language ={
    'languaje' : 'es', 
    
    'Title_Main_Menu' : 'Menu Principal',
    'Text_Plugin_DD' : 'Arrastre para reordenar',
    
    'Tooltip_New_Folder' : 'Nueva carpeta',
    'Tooltip_New_Option' : 'Nueva opción',
    'Tooltip_Edit_Node' : 'Modificar nodo',
    'Tooltip_Del_Node' : 'Eliminar nodo',
    'Tooltip_Save_Menu' : 'Guardar Menu',
    'Tooltip_Reload_Menu' : 'Recargar menu',
    'Tooltip_Reset_Menu' : 'Reiniciar menu',
    'Msg_Window_New_Folder' : 'Por favor, ingrese un nombre de carpeta',
    'Title_Window_New_Folder' : 'Agregar a menu',
    'Msg_Select_Folder' : 'Ninguna carpeta seleccionada',
    'Title_Window_Add_Option' : 'Agregar opción al menu',
    'MenuTree_Title_Fieldset' :'Información Básica',
    'Title_Cancel_Button' : 'Cancelar',
    'Title_Save_Button' : 'Guardar',
    'MenuTree_Text_Add_Event' : 'Agregar Evento',
    'MenuTree_Text_Edit_Event' : 'Modificar Evento',
    'Msg_Saved' : 'Guardando cambios...',
    'Msg_Deleted_Event' : 'Eliminando evento...',
    'Toolbar_Text_Reset_Button' : 'Reiniciar',

    'Msg_Invalid_Form' : 'OOPs!! Formulario no es válido',
    'Msg_Error_Save_Form' : 'Error al guardar formulario',
    'Msg_Failed_Operation' : 'operación fallida',
    'Msg_View_In_New_Tab' : 'Ver en una nueva pestaña',

    'Label_Pagging_by_Page' : 'por página',
    'Label_Pagging_Result' : 'Resultados',
    'Label_Pagging_From' : 'de',
    'Label_Pagging_Page' : 'Página',
    'Label_Pagging_First_Page' : 'Primera página',
    'Label_Pagging_Next_Page' : 'Página siguiente',
    'Label_Pagging_Previous_Page' : 'Página anterior',
    'Label_Pagging_Last_Page' : 'Ultima página',
    'Text_Button_Upd_Grid' : 'Actualizar',
    'Text_Toolbar_Remove_Filters' : 'Quitar filtros',
    'Text_UserInfo_Fullname' : 'usuario solo lectura',
    'Text_ComboFilterOp_Equal' : 'igual',
    'Text_ComboFilterOp_Containing' : 'contiene',
    'Text_ComboFilterOp_Finishing' : 'finaliza con',
    'Text_ComboFilterOp_Starting' : 'inicia con',
    'Text_ComboFilterOp_PlusThan' : 'mayor que',
    'Text_ComboFilterOp_PlusEqualThan' : 'mayor o igual que',
    'Text_ComboFilterOp_LessThan' : 'menor que',
    'Text_ComboFilterOp_LessEqualThan' : 'menor o igual que',
    'Text_ComboFilterOp_Null_Value' : 'Valor nulo',
    'Text_Default_view' : 'Por defecto',

    'List_Help_Meta_Config' : 'Configuración de MetaData',
    'List_Help_Form_Config' : 'Configuración de Formulario',
    'List_Help_Add_Fields' : 'Agregar Campos',
    'List_Help_Add_Details' : 'Agregar Detalles',
    'List_Help_Reset_Meta' : 'Resetear metadata cargada',

    'Tooltip_Grid_Add_Form' : 'Adicionar (formulario)',
    'Tooltip_Grid_Edit_Form' : 'Editar (formulario)',
    'Tooltip_Grid_Del_Record' : 'Borrar registro',
    'Tooltip_Grid_Read_Only' : 'Ver ( sólo lectura )',
    'Tooltip_Grid_Add_Row' : 'Añadir fila',
    'Tooltip_Grid_Copy_Row' : 'Copiar fila',
    'Msg_Select_Record' : 'Ningún registro seleccionado',

    'Tooltip_Filter_Grid_Button' : 'Filtrar',
    'Text_Grid_Filter_By' : 'filtrado por',
    'Text_Toolbar_Advanced_Filter' : 'Filtro QBE avanzado',
    'Text_Toolbar_Search_Field' : 'palabra clave ..',
    'Text_Toolbar_Search_Combo' : 'seleccione el operador',
    'Text_Toolbar_In' :'en ...',
    'Text_Plugin_DD_Grid' : 'Arrastre y suelte para organizar',
    'Text_Validate_Login_Button' : 'validar',
    'Text_Forgotten_Password' : 'contraseña olvidada',
    'Textfield_User_Login' : 'usuario',
    'Textfield_Password_Login' : 'contraseña',
    'Title_Window_Email_Request' : 'su email',
    'Message_Enter_Email' : 'Ingrese su email',
    'Message_Success' : 'Exito',
    'Message_Email_Forgotten_Password' : 'Un email se ha enviado con las instrucciones',
    'Message_Error' : 'Error',
    'Message_Error_Login' : 'Imposible',

    'Text_Toolbar_Detail_Button' : 'Detalles',
    'Error_Loading_Detail_Button' : 'Error cargando',
    'Text_Export_CSV' : 'Exportar CSV',
    'Tooltip_Export_CSV' : 'exportar en formato csv',
    'Text_Plug' : 'Conexión',
    'Text_Grid' : 'Grilla',
    'Text_Print' : 'Imprimir',
    'Message_Succesful_Export_CSV' : 'Exportado a CSV correctamente',
    'Message_Failed_Export_CSV' : 'Error al exportar a CSV',

    'Sorting_Text' : 'Ordenar por',
    'Toolbar_Text_Edit_Button' : 'Modificar',
    'Tooltip_Switch_Edit_Mode' : 'Cambiar a modo edición',
    'Tooltip_Save_Exit_Edition_Button' : 'Guardar y salir de modo edición',
    'Text_Continue_Button' :'Continuar',
    'Tooltip_Save_Continue_Edition_Button' : 'Guardar y continuar',
    'Text_AutoSync' : 'Sincronización automática',
    'Text_Clasify_Button' : 'Clasificar',
    'Tooltip_Clasify_Button' : 'Opciones de ordenamiento',
    'Tooltip_Printing_Options' : 'Opciones de impresión',
    'Text_Actions_Button' : 'Acciones',
    'Tooltip_Actions_Button' : 'Flujo de trabajo básico',
    'Tooltip_Details_Button' : 'Ver detalles',
    'Text_Filters_Button' : 'Filtros',
    'Tooltip_Filters_Button' : 'Filtros personalizados',
    'Text_Close_Button' : 'Cerrar',
    'Tooltip_Exit_Edit_Mode_Button' : 'Salir de modo de edición',

    'Text_Tabs_Button' : 'Tabs',
    'Tooltip_Tabs_Button' : 'Tabs',

    'Text_Sorters_Button' : 'Sorters',
    'Tooltip_Sorters_Button' : 'Sorters',

    'Tooltip_Open_HtmlEditor' : 'Abrir html editor',
    'Text_Return_Button' : 'Volver',
    'StatusBar_Message_Loading' : 'Cargando...',
    'StatusBar_Message_Ready' :'Listo',
    'StatusBar_Message_Sync' : 'Sincronizar..',
    'StatusBar_Text_Clean_Button' : 'Limpiar',
    'StatusBar_Tooltip_Clean_Button' : 'limpiar barra de estado',
    'StatusBar_Text_Task_Button' : 'tarea',
    'StatusBar_Text_Close_Session' : 'Cerrar Sesión',
    'StatusBar_Error_When_Close_Session' : 'La accion no es posible',
    'StatusBar_Text_Command_Button' : 'Comando',

    'Text_Close_Tab' : 'Cerrar pestaña',
    'Text_Close_Other_Tabs' : 'Cerrar demás pestañas',
    'Text_Close_All_Tabs' : 'Cerrar todas las pestañas',

    'Text_Validation_Form' : 'El formulario tiene errores (Haga clic para mas detalles...)',
    'Text_Hide_Errors_Validation_Form' : 'Clic de nuevo para ocultar la lista de eorrores',
    'Text_Submit_Validation_Form' : 'Guardando...',

    'Message_Error_SavePCI' : 'Error al guardar PCI',
    'Message_Error_Reporting' : 'Error en lanzar informe',

    'Title_Main_Panel' : 'Panel Raiz',
    'Title_Form_Panel' : 'Formulario',
    'Title_Panel_Tools' : 'Herramientas',

    'Tree_Concept_Details_Text' : 'texto',
    'Tree_Concept_Details_Detail' : 'detalle del concepto',
    'Tree_Details_Field' : 'detalle del campo',


    'Protofield_Fields' : 'campos',
    'Protofield_Text' : 'texto',
    'Protofield_Req' : 'requerido',
    'Protofield_ROnly' : 'solo lectura',
    'Protofield_Field_Type' : 'tipo de campo',
    'Protofield_Zoom_Model' : 'Modelo de zoom',
    'Protofield_fk_Field' :'fkCampo',
    'Protofield_fk_Id' : 'fkId',
    'Protofield_Ix' : 'Ix',
    'Protofield_Header' : 'Encabezado',
    'Protofield_Tooltip' : 'tooltip',
    'Protofield_Default_Value' : 'valor por defecto',
    'Protofield_vType' : 'Tipo de validación',
    'Protofield_choices' : 'Elecciones',
    'ProtoPcl_Edition_Tool' : 'Meta edition tool',
    'ProtoPcl_Add_Instance' : 'Adicionar instancia de',
    'ProtoPcl_Del_Current' : 'Borrar actual',
    'ProtoToolbar_Save_Preview' : 'Guardar vista previa',
    'ProtoToolbar_Upd_Def' :'Actualizar definición',
    'ProtoToolbar_Reload' :'Recargar',
    'ProtoToolbar_Add_Node' :'Adicionar nodo',
    'ProtoToolbar_Del_Current_Node' :'Borrar el nodo actual',
    'ProtoToolbar_Show_Current_Meta' :'Mostrar Meta actual',
    'ProtoToolbar_Show_Help' : 'Mostrar ayuda',

    'Text_Enter_User_Login' : 'Debe ingresar un usuario',
    'Text_Validating_Info_User' : 'Autenticando ...',
    'Text_No_Aplications' : 'No hay aplicaciones asignadas',
    'Text_General_Information' : 'Información',
    'Text_Error_In_Action' : 'La acción no fue posible',

    'Title_Aut_View' : 'Autorización',
    'Header_Column_Grid_App' : 'Aplicación',
    'Header_Column_Grid_App_Id' : 'Id',
    'Header_Column_Grid_Env' : 'Entorno',
    'Header_Column_Grid_Env_Id' : 'Id',

    'Title_Login_View' : 'Autenticación',
    'Text_Combo_App' : 'Aplicación',
    'Text_Combo_Env' : 'Entorno',
    'Text_Accept_Button' : 'Aceptar',
    'Text_Button_Load_App' : 'Cargar aplicación ',
    'Text_Button_Close_Session' : 'Cerrar sesión',

    'HelpQBE_Tooltip_PlusThan_Button' : 'mayor que',
    'HelpQBE_Tooltip_LessThan_Button' : 'menor que',
    'HelpQBE_Tooltip_PlusEqualThan_Button' : 'mayor o igual que',
    'HelpQBE_Tooltip_LessEqualThan_Button' : 'menor o igual que',
    'HelpQBE_Tooltip_Different_Button' : 'diferente',
    'HelpQBE_Tooltip_Between_Button' : 'entre',
    'HelpQBE_Tooltip_Containing_Button' : 'contiene',

    'HelpQBE_Label_Pagging_DisplayMsg' : 'registros {0} - {1} de {2}',
    'HelpQBE_Label_Pagging_EmptyMsg' : 'no hay registros', 
    'HelpQBE_Window_Title' : 'Asistente QBE'
}
