# -*- coding' : utf-8 -*-

__language ={
    'languaje' : 'fr', 
             
    'Title_Main_Menu' : 'Menu principal',
    'MenuTree_DD_Text' : 'Glisser pour réorganiser',
    'Tooltip_New_Folder' : 'Nouveau dossier',
    'Tooltip_New_Option' : 'Nouvelle option',
    'Tooltip_Edit_Node' : 'Modifier noeud',
    'Tooltip_Del_Node' : 'Supprimer noeud',
    'Tooltip_Save_Menu' : 'Enregistrer menu',
    'Tooltip_Reload_Menu' : 'Recharger menu',
    'Tooltip_Reset_Menu' : 'Réinitialiser menu',
    'Msg_Window_New_Folder' : "S'il vous plaît entrez le nom du dossier",
    'Title_Window_New_Folder' : "Ajouter menu",
    'Msg_Select_Folder' : 'Dossier non sélectionné',
    'Title_Window_Add_Option' : "Ajouter une option de menu",
    'MenuTree_Title_Fieldset' : 'Information de base',
    
    'Text_Cancel_Button' : 'Annuler',
    'Text_Save_Button' : 'Enregistrer',
    'Text_New_Button' : 'Nouveau',
    'Text_Edit_Button' : 'Éditer',
    'Text_SaveMs_Button' : 'Enregistrer',
    'Text_SaveDt_Button' : 'Enregistrer details',
    
    'MenuTree_Text_Add_Event' : "Ajouter événement ",
    'MenuTree_Text_Edit_Event' : "Modifier événement",
    'Msg_Saved' : 'Enregistrement des modifications ...',
    'Msg_Deleted_Event' : "Suppression événement ...",
    
    'Msg_Invalid_Form' : "OOPS! Formulaire non valide",
    'Msg_Error_Save_Form' : 'Enregistrer le formulaire échoué',
    'Msg_Failed_Operation' : "Opération échouée",
    'Msg_Confirm_Delete_Operation' : 'Etes-vous sûr?',
    
    'Title_Msg_Confirm_Delete' : 'Confirmation de la suppression',

    'GridNav_In_New_Tab' : 'Voir dans un nouvel onglet',
    'GridNav_PageSize' : 'par page',
    'GridNav_Current' : 'Résultats',
    'GridNav_Total' : 'de',
    'GridNav_Page' : 'Page',
    'GridNav_First_Page' : 'Première page',
    'GridNav_Next_Page' : 'Page suivante',
    'GridNav_Previous_Page' : 'Page précédente',
    'GridNav_Last_Page' : 'Dernière page',
    'GridNav_Refresh' : 'Rafraîchir',
    
    'Text_Toolbar_Remove_Filters' : 'Supprimer filtres',
    'Text_UserInfo_Fullname' :'Utilisateur en lecture seule',
    'Text_ComboFilterOp_Equal' : 'égal',
    'Text_ComboFilterOp_Containing' : 'qui contient',
    'Text_ComboFilterOp_Finishing' : 'qui finisse par',
    'Text_ComboFilterOp_Starting' : 'qui commence par',
    'Text_ComboFilterOp_PlusThan' : 'plus grand que',
    'Text_ComboFilterOp_PlusEqualThan' : 'plus grand ou égal que',
    'Text_ComboFilterOp_LessThan' : 'plus petit que',
    'Text_ComboFilterOp_LessEqualThan' : 'plus petit ou égal que',
    'Text_ComboFilterOp_Null_Value' : 'valeur nulle',
    'Text_Default_view' : 'par défaut',
  
    'MetaConfig_Meta_Config' : 'Méta',
    'MetaConfig_Form_Config' : 'Formulaire',
    'MetaConfig_Custom_Config' : 'Personnalisation',
    'MetaConfig_Base_Config' : 'Configuration',
    'MetaConfig_Add_Fields' : 'Champs',
    'MetaConfig_Add_Details' : 'Détails',
    'MetaConfig_Reset_Meta' : 'Réinitialiser méta chargé',

    'GridBtn_Ttip_Add_Form' : 'Ajouter (formulaire)',
    'GridBtn_Ttip_Edit_Form' : 'Éditer (formulaire)',
    'GridBtn_Ttip_Del_Record' : 'Supprimer enregistrement',
    'GridBtn_Ttip_Read_Only' : 'Visualiser ( en lecture seule )',
    'GridBtn_Ttip_Add_Row' : 'Ajouter ligne',
    'GridBtn_Ttip_Copy_Row' : 'Copier ligne',
    'GridBtn_Ttip_Edit_Diagram':'Éditer diagramme',
    'GridAction_NoRecord' : 'aucun enregistrement sélectionné',

    'Tooltip_Filter_Grid_Button' : 'Filtrer',
    'Text_Grid_Filter_By' : 'filtré par',
    'Text_Toolbar_Advanced_Filter' :'Filtre avancé QBE',
    'Text_Toolbar_Search_Field' : 'mots-clés ..',
    'Text_Toolbar_Search_Combo' : 'sélectionner opérator',
    'Text_Toolbar_In' : 'dans ...',
    'ProtoList_DD_Text' : 'Glisser-déposer pour réorganiser',
    
    'Text_Validate_Login_Button' : 'Connexion',
    'Text_Forgotten_Password' : 'Mot de passe perdu',
    'Textfield_User_Login' : 'Utilisateur',
    'Textfield_Password_Login' : 'Mot de passe',
    'Title_Window_Email_Request' : 'Votre courriel',
    'Message_Enter_Email' : 'Saisissez votre courriel',
    'Message_Success' : 'Succès',
    'Message_Email_Forgotten_Password' : 'Un courriel a été envoyée avec les instructions',
    'Message_Error' : 'Erreur',
    'Message_Error_Login' : 'Impossible',

    'Grid_Detail_Title' : 'Navigation',
    'Grid_Detail_Error' : 'Erreur lors du chargement',
    'Grid_ExportCSV' : 'Exporter CSV',
    'Grid_ExportCSV_Ttip' : 'Exportation au format CSV',
    'Grid_ExportCSV_Ok' : 'Exporter CSV réussi',
    'Grid_ExportCSV_Err' : "Échec de l'exportation CSV",

    'Text_Plug' : 'Plug',
    'Text_Print' : 'Imprimer',
    'Text_Config' : 'Configuration',
    'Text_Grid' :'Grille',

    'Grid_Sort_Title' : 'Classer par',
    'Grid_Edit_Title' : 'Éditer',
    'Grid_Edit_Ttip' : 'Passer en mode edition',
    'Grid_EditSave_Title' : "Enregistrer et quitter le mode d'édition",
    'Grid_EditSaveCont_Title' : 'Continuer',
    'Grid_EditSaveCont_Ttip' : 'Enregistrer et continuer',
    'Grid_EditAutoSync_Title' : 'Auto synchroniser',
    
    'Text_Clasify_Button' : 'Classer',
    'Tooltip_Clasify_Button' : 'Options de tri',
    'Tooltip_Printing_Options' : "Options d'impression",
    'Tooltip_Config_Button' : "Configuration d'options",
    'Text_Actions_Button' : 'Actions',
    'Tooltip_Actions_Button' : 'Exécuter des actions',
    'Tooltip_Details_Button' : 'Navigation vers',
    'Text_Filters_Button' : 'Filtres',
    'Tooltip_Filters_Button' : 'Filtres personnalisés',
    'Text_Close_Button' : 'Fermer',
    
    'Text_Exit_Edit_Mode_Button' : 'Sortir edition',
    'Tooltip_Exit_Edit_Mode_Button' : 'Sortir mode édition',

    'Text_Tabs_Button' : 'Onglets',
    'Tooltip_Tabs_Button' : 'Onglets',

    'Text_Sorters_Button' : 'Trieurs',
    'Tooltip_Sorters_Button' : 'Trieurs',

    'Tooltip_Open_HtmlEditor' : 'Ouvrir éditeur HTML',
    'Text_Return_Button' :'Retour',
    'StatusBar_Message_Loading' : 'Chargement ...',
    'StatusBar_Message_Ready' : 'Prêt',
    'StatusBar_Message_Sync' : 'Synchroniser..',
    'StatusBar_Text_Clean_Button' : 'Effacer',
    'StatusBar_Tooltip_Clean_Button' : "Fermer tous les onglets",
    'StatusBar_Text_Task_Button' : 'tâche',
    'StatusBar_Text_Close_Session' : 'Fermer la session',
    'StatusBar_Error_When_Close_Session' : "Impossible de fermer la session",
    'StatusBar_Text_Command_Button' : 'commandement',

    'Text_Close_Tab' : "Fermer onglet",
    'Text_Close_Other_Tabs' : 'Fermer les autres onglets',
    'Text_Close_All_Tabs' : 'Fermer tous les onglets',

    'Text_Validation_Form' : 'Le formulaire contient des erreurs (cliquez pour voir les détails ...)',
    'Text_Hide_Errors_Validation_Form' : 'Cliquez à nouveau pour masquer la liste des erreurs',
    'Text_Submit_Validation_Form' : 'Enregistrement en cours ...',

    'Message_Error_SaveProtoObj' : "Échec d'enregistrement PCI",
    'Message_Error_Reporting' : 'Échec de création du rapport',

    'Title_Main_Panel' : 'Paneau principal',
    'Title_Form_Panel' : 'Éléments du formulaire',
    'Title_Panel_Tools' : 'Outils du formulaire',

    'Tree_Concept_Details_Text' : 'texte',
    'Tree_Concept_Details_Detail' : 'détail du concept',
    'Tree_Details_Field' : 'détail du champ',

    'Protofield_Fields' : 'champs',
    'Protofield_Text' : 'Nom champ',
    'Protofield_Req' : 'Requis',
    'Protofield_ROnly' : 'Lecture seule',
    'Protofield_Field_Type' : 'Type de champ',
    'Protofield_Zoom_Model' : 'Zoom Modèle',
    'Protofield_fk_Field' : 'Clé étrangère',
    'Protofield_fk_Id' : 'ID clé étrangère',
    'Protofield_Ix' : 'Ix',
    'Protofield_Header' : 'En-tête',
    'Protofield_Tooltip' : 'infobulle',
    'Protofield_Default_Value' : 'valeur par défaut',
    'Protofield_vType' : 'vType',
    'Protofield_choices' : 'choix',
    'ProtoPcl_Edition_Tool' : 'Outil édition Méta',
    'ProtoPcl_Add_Instance' : 'Ajouter une instance de',
    'ProtoPcl_Del_Current' : 'Supprimer instance actuelle',
    'ProtoToolbar_Save_As' : 'Enregistrer sous',
    'ProtoToolbar_Upd_Def' :"Mettre à jour la définition",
    'ProtoToolbar_Reload' :'Recharger',
    'ProtoToolbar_Add_Node' :'Ajouter noeud',
    'ProtoToolbar_Del_Current_Node' :'Effacer noeud actuel',
    'ProtoToolbar_Show_Current_Meta' :'Voir Meta actuelle',
    'ProtoToolbar_Show_Help' : "Afficher l'aide",

    'Text_Enter_User_Login' : 'Vous devez entrer un nom',
    'Text_Validating_Info_User' : 'Authentification en procès ...',
    'Text_No_Aplications' : 'Aucune application affectée',
    'Text_General_Information' :"Information",
    'Text_Error_In_Action' : "L'action n'a pas été possible",

    'Title_Aut_View' : 'Autorisation',
    'Header_Column_Grid_App' : 'Application',
    'Header_Column_Grid_App_Id' : 'Id',
    'Header_Column_Grid_Env' : 'Environnement',
    'Header_Column_Grid_Env_Id' : 'Id',

    'Title_Login_View' : 'Authentification',
    'Text_Combo_App' : 'Application',  
    'Text_Combo_Env' : 'Environnement',
    'Text_Accept_Button' : 'Accepter',
    'Text_Button_Load_App' :'Charger application',
    'Text_Button_Close_Session' : 'Fermer la session',

    'HelpQBE_Tooltip_PlusThan_Button' : 'plus grand que',
    'HelpQBE_Tooltip_LessThan_Button' : 'plus petit que',
    'HelpQBE_Tooltip_PlusEqualThan_Button' : 'plus grand ou égal que',
    'HelpQBE_Tooltip_LessEqualThan_Button' : 'plus petit ou égal que',
    'HelpQBE_Tooltip_Different_Button' : 'différent',
    'HelpQBE_Tooltip_Between_Button' : 'entre',
    'HelpQBE_Tooltip_Containing_Button' : 'qui contient',
    'HelpQBE_GridNav_DisplayMsg' : 'registres {0} - {1} de {2}',
    'HelpQBE_GridNav_EmptyMsg' : 'no registres',
    'HelpQBE_Window_Title' : 'Aider QBE',
    
    
    'Menu_Update_Diagram' : 'Mettre à jour le diagramme',
    'Menu_Search_Table' : 'Chercher des tables dans la DB',
    'Menu_Manage_Diagrams' : 'Gérer diagrammes',
    'Menu_Database_Title' : 'Base de données',
    'Menu_Add_Recursive_Association' : 'Ajouter association récursive',
    'Menu_Add_Input_Port' : 'Ajouter un port d\'entrée',
    'Menu_Add_Output_Port' : 'Ajouter un port de sortie',
    'Menu_Remove_Unused_Ports' : 'Retirer les ports non utilisés',
    
    'Text_Undo_Button' : 'Défaire',
    'Text_Redo_Button' : 'Refaire',
    'Text_Delete_Button' : 'Effacer',
    'Text_ZoomIn_Button' : 'Zoom avant',
    'Text_ZoomOut_Button' : 'Zoom arrière',
    'Text_Save_Diagram_Button' : 'Enregistrer diagramme',
    'Text_Commit_Changes_Button' : 'Mettre à jour la base de données',
    'Text_Add_Button' : 'Ajouter',
    'Text_UpdateDiagram_Button' : 'Mettre à jour le diagramme',
    'Text_OpenDiagram_Button' : 'Ouvrir diagramme',
    'Text_Export_Image': 'Imprimer diagramme',
    
    'GridColumn_Name' : 'Nom',
    'GridColumn_Datatype' : 'Type de données',
    'GridColumn_Required' : 'Requis',
    
    'Title_Attributes' : 'Attributs',
    'Title_Work_Diagram' : 'Diagramme de travail: ',
    'Title_Diagrams' : 'Diagrammes',
    
    'Label_Dependency':'Dépendance',
    'Label_Table_Name':'Nom de la table',
    'Label_Connector_Name':'Nom du connecteur',
    
    'Message_Saving_Data' : 'Sauvegarde de vos données, veuillez patienter s\'il vous plaît...',
    'Message_Creating_Objects' : 'Création d\'objets dans la base de données, veuillez patienter s\'il vous plaît...',
    'Message_Diagram_Synchronized' : 'Le diagramme a été synchronisé!',
    'Message_Error_Diagram_Synchronized' : 'Le système n\'a pas pu synchroniser le diagramme, veuillez réessayer plus tard!',
    'Message_Add_Table_Canvas' : 'Chargement ...',
    
    'Warning_Delete_Active_Diagram' : 'Vous ne pouvez pas supprimer le diagramme actif!',
    'Warning_Diagram_Already_Open' : 'Le diagramme sélectionné est déjà ouvert!',
    
    'Label_Left': 'Gauche',
    'Label_Right': 'Droite',
    'Label_Top': 'Haut',
    'Label_Bottom': 'Bas'
}