-- drop table rai_domaineaffaires;
drop table rai_indexdesdonnees;
drop table rai_specifications;
drop table rai_projet;
drop table rai_regroupementdesmodeles;
drop table rai_entite;
drop table rai_reglesgestion;
drop table rai_elementdonnee;
drop table rai_porteereglegestion;
drop table rai_raccordement;
drop table rai_modeleraccordement;
drop table rai_relation;
drop table rai_modele;
drop table rai_norme;
drop table rai_typeregle;
drop table rai_codagenormalise;
