from prototype.ProjectTest import ProjectTest
from prototype.ModelTest import ModelTest
from prototype.EntityTest import EntityTest
#from prototype.PropertyBaseTest import PropertyBaseTest
from prototype.PropertyTest import PropertyTest
#from prototype.RelationshipTest import RelationshipTest
from prototype.PropertyModelTest import PropertyModelTest
from prototype.PropertyEquivalenceTest import PropertyEquivalenceTest
from prototype.PrototypeTest import PrototypeTest
#from prototype.ProtoTableTest import ProtoTableTest
from prototype.DiagramTest import DiagramTest
from prototype.DiagramEntityTest import DiagramEntityTest
from prototype.ServiceTest import ServiceTest
from prototype.ServiceRefTest import ServiceRefTest
