from alltests.testPrototype.testmodels.DiagramEntityTest import *
from alltests.testPrototype.testmodels.DiagramTest import *
from alltests.testPrototype.testmodels.EntityTest import *
from alltests.testPrototype.testmodels.ModelTest import *
from alltests.testPrototype.testmodels.ProjectTest import *
from alltests.testPrototype.testmodels.PropertyTest import *
from alltests.testPrototype.testmodels.PropertyEquivalenceTest import *
from alltests.testPrototype.testmodels.ProtoTableTest import *
from alltests.testPrototype.testmodels.PrototypeTest import *
from alltests.testPrototype.testmodels.RelationshipTest import *
