from alltests.testprototype.testmodels.DiagramEntityTest import *
from alltests.testprototype.testmodels.DiagramTest import *
from alltests.testprototype.testmodels.EntityTest import *
from alltests.testprototype.testmodels.ModelTest import *
from alltests.testprototype.testmodels.ProjectTest import *
from alltests.testprototype.testmodels.PropertyBaseTest import *
from alltests.testprototype.testmodels.PropertyTest import *
from alltests.testprototype.testmodels.PropertyEquivalenceTest import *
from alltests.testprototype.testmodels.PropertyModelTest import *
from alltests.testprototype.testmodels.ProtoTableTest import *
from alltests.testprototype.testmodels.PrototypeTest import *
from alltests.testprototype.testmodels.RelationshipTest import *
from alltests.testprototype.testmodels.ServiceTest import *
from alltests.testprototype.testmodels.ServiceRefTest import *